
name: Android Instrumented Test

on:
  workflow_call:
    inputs:
      api_level:
        required: true
        type: string
      arch:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  instrumented-test:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Install Gradle Wrapper
        run: gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{inputs.api_level}}
          arch: ${{inputs.arch}}
          target: ${{inputs.target}}
          profile: Pixel 7
          script: ./gradlew :fuse:connectedCheck