
name: Android Instrumented Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin

jobs:
  API-24:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{env.JAVA_VERSION}}
        distribution: ${{env.JAVA_DISTRIBUTION}}
        cache: gradle
    - name: Install Gradle Wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        arch: x86_64
        target: google_apis
        script: ./gradlew :fuse:connectedCheck
  